// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeY0wPNp8HwIpu2DQU-DYgM9Abl29QJgI',
    appId: '1:86335933030:web:d4f0c4fa20bdb2b2f03ba7',
    messagingSenderId: '86335933030',
    projectId: 'k-list-collection',
    authDomain: 'k-list-collection.firebaseapp.com',
    storageBucket: 'k-list-collection.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkHwMuZCTfa0MmuxUYQw-m9qiYz_0Sf9o',
    appId: '1:86335933030:android:c1e6945d0c5aa46ff03ba7',
    messagingSenderId: '86335933030',
    projectId: 'k-list-collection',
    storageBucket: 'k-list-collection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KB7_PrqRWCYpr2MY57fhohM7tUh_y0M',
    appId: '1:86335933030:ios:63dd7316c12050c9f03ba7',
    messagingSenderId: '86335933030',
    projectId: 'k-list-collection',
    storageBucket: 'k-list-collection.firebasestorage.app',
    iosBundleId: 'com.example.kList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8KB7_PrqRWCYpr2MY57fhohM7tUh_y0M',
    appId: '1:86335933030:ios:63dd7316c12050c9f03ba7',
    messagingSenderId: '86335933030',
    projectId: 'k-list-collection',
    storageBucket: 'k-list-collection.firebasestorage.app',
    iosBundleId: 'com.example.kList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeY0wPNp8HwIpu2DQU-DYgM9Abl29QJgI',
    appId: '1:86335933030:web:b9234664be6b81b0f03ba7',
    messagingSenderId: '86335933030',
    projectId: 'k-list-collection',
    authDomain: 'k-list-collection.firebaseapp.com',
    storageBucket: 'k-list-collection.firebasestorage.app',
  );
}
